version: "3.9"

services:
  config:
    image: loctran070699/podcast-config-server:latest
    ports:
      - "8080:8080"
    networks:
      - podcast-network
    healthcheck:
      test: [ "CMD-SHELL", "wget --spider -q http://localhost:8080/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 2

  eureka:
    image: loctran070699/podcast-eureka-server:latest
    ports:
      - "8070:8070"
    networks:
      - podcast-network
    depends_on:
      config:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: eureka
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: optional:configserver:http://config:8080
    healthcheck:
      test: [ "CMD-SHELL", "wget --spider -q http://localhost:8070/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 2


  video:
    image: loctran070699/podcast-video-api:latest
    ports:
      - "8000:8000"
    networks:
      - podcast-network
    depends_on:
      eureka:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: video
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: optional:configserver:http://config:8080
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8070/eureka/

  account:
    image: loctran070699/podcast-account-api:latest
    ports:
      - "8100:8100"
    networks:
      - podcast-network
    depends_on:
      eureka:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: account
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: optional:configserver:http://config:8080
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8070/eureka/
networks:
  podcast-network: